# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f36a9015f9fa152fa12fd46039e342a6ccf16c56ef8ef26a2727081ac1ca47fea0c745aee55b2e3975c4f69117094a0db16421a3b09e6097e4fdd8c629689b5

test:
  secret_key_base: 8ba12792fe3f0513a883b4fa27f6e8e6855c9a9cea0af1d246b244e1fb3093d3788a417ddd7b898879eac631766947144eee5015e88d7aa9bbbb0a6d4f9f9227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
